site_name: see-agreement

repo_name: saveweb/see-agreement
repo_url: https://github.com/saveweb/see-agreement

theme:
    favicon: src/favicon.png
    icon:
        logo: material/account-circle
    font: false
    palette:
        - media: "(prefers-color-scheme: light)"
          primary: blue
          scheme: default
          toggle:
              icon: material/toggle-switch-off-outline
              name: 切换到暗模式
        - media: "(prefers-color-scheme: dark)"
          primary: blue
          scheme: slate
          toggle:
              icon: material/toggle-switch
              name: 切换到亮模式
    name: material
    language: zh                # 中文，解决中文搜索问题

use_directory_urls: false       # URL 风格
edit_uri: ""                    # 隐藏编辑按钮

markdown_extensions:
    - attr_list                 # https://squidfunk.github.io/mkdocs-material/reference/images/ # 增加css-html样式，例如按钮，比如图片定义大小，caption
    # - nl2br                   # newline-to-break markdown 非严格换行
    - toc:
          permalink: "#"        # heading anchor
          slugify: !!python/name:pymdownx.slugs.uslugify # 解决中文标题解析问题
    - admonition                # 突出显示一些东西，比如 !!!info|bug|tips之类
    - codehilite:
          guess_lang: false
          linenums: false
    - footnotes                 # 支持脚注[^1]
    - meta
    - def_list                  # 支持有序、无序、任务列表
    - pymdownx.tasklist
    # - pymdownx.arithmatex     # 数学公式latex支持
    - pymdownx.betterem:
          smart_enable: all
    - pymdownx.details
    # - pymdownx.pathconverter:
    #     base_path: ''         # default: ''
    #     relative_path: ''     # default ''
    #     absolute: false       # default: false
    #     tags: 'a script img link object embed'
    # - pymdownx.emoji:         # 支持图标icons和表情渲染，比如:smile:
    # emoji_generator: !!python/name:pymdownx.emoji.to_png
    - pymdownx.highlight        # 代码块相关
    - pymdownx.inlinehilite     # 代码块相关
    - pymdownx.superfences      # 代码块相关
    - pymdownx.tabbed           # 标签页 https://squidfunk.github.io/mkdocs-material/reference/content-tabs/ # C++/python 代码例子切换
    - pymdownx.snippets
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.critic           # 支持 markdown 高亮==、删除、注解等高级样式
    - pymdownx.keys             # 支持 快捷键渲染

plugins:
    - search
    - abs-to-rel                # 绝对路径转相对路径 https://pypi.org/project/mkdocs-abs-rel-plugin/
    # - pdf-export              # 导出为 PDF 格式，不过对于此 Wiki 来说，耗时过多。
    # - roamlinks               # 这是自动将链接转化为易于 mkdocs 的插件
    #- autolinks
    - exclude:
          glob:
              - "src/[HD]/*"
              - "mkdocs/本地/*"
              - "*.tmp"
              - "*.gz"
          regex:
              - '.*\.(tmp|bin|tar)$'
    - redirects:                # 重定向插件 https://github.com/datarobot/mkdocs-redirects
        redirect_maps:
            # 比如 "website/立场新闻.md": "company/立场新闻.md" # 主要是在更换了 URL 后，防止用户找不到页面使用

extra:
    # generator: false
    social:
        - icon: fontawesome/brands/telegram
          link: https://t.me/xxx
        - icon: material/email-outline
          link: mailto:xxx@xxx.xxx

extra_css:
    - "css/external_link_icon.css"
    - "css/footnotes.css"

# copyright:                  # 取消 generator 注释后才能填写

